### ISSUE TITLE
Error: Cannot find module 'exit'

### ISSUE THREAD

**Issue by magsout** [cssnext/cssnext#54]
Using the command `npm run build` on the [grid component cssrecipes](https://github.com/cssrecipes/grid) I get this error: 

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'exit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mac/Sandbox/grid/node_modules/cssnext/bin/cssnext:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I tested with version `0.5.0`, it works, but since `0.6.0` I get an error.

**Comment by magsout** [comment]
I reopen issue because I have still an error :

```
MacBook-Air:css GuillaumeDEMESY$ cssnext admin.css output.css

module.js:340
    throw err;
          ^
Error: Cannot find module 'exit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cssnext/bin/cssnext:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by MoOx** [comment]
What gives: `./node_modules/.bin/cssnext --version` ?

**Comment by MoOx** [comment]
If you use it via a plugin, please desinstall & reinstall it, semver should do the work for you.

**Comment by magsout** [comment]
oups my bad, I had a -g install unbuild cssnext@0.6.5

**Comment by MoOx** [comment]
Don't use npm install -g for projects :)
Only for tools like [trash](https://www.npmjs.com/package/trash)
