### ISSUE TITLE
npm ERR! Failed at the caniuse-api@1.2.2 postinstall script

### ISSUE THREAD

**Issue by Paulmicha** [cssnext/cssnext#79]
Tentative installation (Ubuntu 14.04.2 LTS, node -v v0.10.36, npm -v 1.4.28) - error message dump :

```
npm install cssnext
|
> caniuse-api@1.2.2 postinstall /srv/i.paulmichalet.lan-0-25.io/sites/all/themes/ipaul/css/node_modules/cssnext/node_modules/caniuse-api
> node -e "require('shelljs/global');if(test('-d', 'dist'))exec('node dist/generate-features.js')"

module.js:340
    throw err;
          ^
Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3

npm ERR! caniuse-api@1.2.2 postinstall: `node -e "require('shelljs/global');if(test('-d', 'dist'))exec('node dist/generate-features.js')"`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the caniuse-api@1.2.2 postinstall script.
npm ERR! This is most likely a problem with the caniuse-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "require('shelljs/global');if(test('-d', 'dist'))exec('node dist/generate-features.js')"
npm ERR! You can get their info via:
npm ERR!     npm owner ls caniuse-api
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "cssnext"
npm ERR! cwd /srv/i.paulmichalet.lan-0-25.io/sites/all/themes/ipaul/css
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by MoOx** [comment]
It seems shelljs has not been installed correctly. Can you try reinstalling cssnext ?

```console
$ npm rm cssnext
$ npm i cssnext
```

If problem persist try cleaning shelljs npm cache

```console
$ rm -rf ~/.npm/shelljs
```

**Comment by Paulmicha** [comment]
Still fails, here's what I tried :

1. `npm rm cssnext`, got : `npm WARN uninstall not installed in /srv/i.paulmichalet.lan-0-25.io/sites/all/themes/ipaul/css/node_modules: "cssnext"`
Then same error when attempting `npm i cssnext`

2. `rm -rf ~/.npm/shelljs` then `npm i cssnext` ->  same error

3. `rm -rf ~/.npm/shelljs`, then `npm install shelljs -g` and `npm i cssnext` ->  same error

Here's the output of `npm install shelljs -g` :
```
/usr/bin/shjs -> /usr/lib/node_modules/shelljs/bin/shjs
shelljs@0.3.0 /usr/lib/node_modules/shelljs
```

**Comment by MoOx** [comment]
Just in case, which version of node are you using ?
@nyalab did you push anything to caniuse-api recently ? (Just checking from mobile ^^)

**Comment by Paulmicha** [comment]
0.10.36

**Comment by MoOx** [comment]
Cannot reproduce for now.
This is weird because caniuse-api correctly have https://github.com/Nyalab/caniuse-api/blob/master/package.json#L15
Also tests are ok on travis, which is a linux setup. Not sure what the fuck is happening :/
Try `rm -rf ~/.npm` maybe ? `rm -rf node_modules`, and reinstall cssnext ?

**Comment by MoOx** [comment]
@Paulmicha did you still have this issue ?

**Comment by Paulmicha** [comment]
\o/ \o/ \o/ It worked, thx a lot ^^
Wonder if there was an interaction with my existing suitcss (global) installation or something...
Anyways :+1:

**Comment by jedmao** [comment]
@MoOx I'm not having as much luck as @Paulmicha. Here's my env:

```
CentOS release 6.5 (Final)
node v0.10.33
npm v1.3.6
```

I did as you requested, running the following:

```
rm -rf ~/.npm
rm -rf node_modules
```

But when I try a fresh install of cssnext, like so:

```
npm install --save-dev cssnext
```

I get the following errors:

```
npm ERR! Error: UNKNOWN, mkdir '/vagrant/node_modules/cssnext/node_modules/caniu
se-api/node_modules/lodash.uniq/node_modules/lodash.createcallback/node_modules/
lodash._basecreatecallback/node_modules/lodash.bind/node_modules/lodash._createw
rapper/node_modules'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "--save-dev" "cssnext"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /vagrant/node_modules/cssnext/node_modules/caniuse-api/node_module
s/lodash.uniq/node_modules/lodash.createcallback/node_modules/lodash._basecreate
callback/node_modules/lodash.bind/node_modules/lodash._createwrapper/node_module
s
npm ERR! fstream_path /vagrant/node_modules/cssnext/node_modules/caniuse-api/nod
e_modules/lodash.uniq/node_modules/lodash.createcallback/node_modules/lodash._ba
secreatecallback/node_modules/lodash.bind/node_modules/lodash._createwrapper/nod
e_modules/lodash.isfunction
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: UNKNOWN, mkdir '/vagrant/node_modules/cssnext/node_modules/caniu
se-api/node_modules/lodash.uniq/node_modules/lodash.createcallback/node_modules/
lodash._basecreatecallback/node_modules/lodash.bind/node_modules/lodash._createw
rapper/node_modules'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "--save-dev" "cssnext"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /vagrant/node_modules/cssnext/node_modules/caniuse-api/node_module
s/lodash.uniq/node_modules/lodash.createcallback/node_modules/lodash._basecreate
callback/node_modules/lodash.bind/node_modules/lodash._createwrapper/node_module
s
npm ERR! fstream_path /vagrant/node_modules/cssnext/node_modules/caniuse-api/nod
e_modules/lodash.uniq/node_modules/lodash.createcallback/node_modules/lodash._ba
secreatecallback/node_modules/lodash.bind/node_modules/lodash._createwrapper/nod
e_modules/lodash._basebind
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: UNKNOWN, mkdir '/vagrant/node_modules/cssnext/node_modules/caniu
se-api/node_modules/lodash.uniq/node_modules/lodash.createcallback/node_modules/
lodash._basecreatecallback/node_modules/lodash.bind/node_modules/lodash._createw
rapper/node_modules'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "--save-dev" "cssnext"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /vagrant/node_modules/cssnext/node_modules/caniuse-api/node_module
s/lodash.uniq/node_modules/lodash.createcallback/node_modules/lodash._basecreate
callback/node_modules/lodash.bind/node_modules/lodash._createwrapper/node_module
s
npm ERR! fstream_path /vagrant/node_modules/cssnext/node_modules/caniuse-api/nod
e_modules/lodash.uniq/node_modules/lodash.createcallback/node_modules/lodash._ba
secreatecallback/node_modules/lodash.bind/node_modules/lodash._createwrapper/nod
e_modules/lodash._basecreatewrapper
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0
```

**Comment by MoOx** [comment]
@jedmao You error seems completely different, so you might open a new issue.
But before that please try on at least node 0.12  + npm 2+, you are using very old versions. (npm3 is already planned)
